// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3_k-WXmnBXaXyAYiif21g-gDyR19WSJg',
    appId: '1:1027060155144:web:b09bcb3dbd4c1544bea2bd',
    messagingSenderId: '1027060155144',
    projectId: 'craftybay-4ba76',
    authDomain: 'craftybay-4ba76.firebaseapp.com',
    storageBucket: 'craftybay-4ba76.firebasestorage.app',
    measurementId: 'G-Z1W7N5JGWL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPrHQapL1Oj-S2tVNeLyNNbQ8vceu83jw',
    appId: '1:1027060155144:android:331c6e28db31ee3cbea2bd',
    messagingSenderId: '1027060155144',
    projectId: 'craftybay-4ba76',
    storageBucket: 'craftybay-4ba76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoUQINpbZObnjLbskTkTFYXD3zn34h3UM',
    appId: '1:1027060155144:ios:cde58889e77c526bbea2bd',
    messagingSenderId: '1027060155144',
    projectId: 'craftybay-4ba76',
    storageBucket: 'craftybay-4ba76.firebasestorage.app',
    iosBundleId: 'com.example.crafyBay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoUQINpbZObnjLbskTkTFYXD3zn34h3UM',
    appId: '1:1027060155144:ios:cde58889e77c526bbea2bd',
    messagingSenderId: '1027060155144',
    projectId: 'craftybay-4ba76',
    storageBucket: 'craftybay-4ba76.firebasestorage.app',
    iosBundleId: 'com.example.crafyBay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3_k-WXmnBXaXyAYiif21g-gDyR19WSJg',
    appId: '1:1027060155144:web:5f1b0005092aff3bbea2bd',
    messagingSenderId: '1027060155144',
    projectId: 'craftybay-4ba76',
    authDomain: 'craftybay-4ba76.firebaseapp.com',
    storageBucket: 'craftybay-4ba76.firebasestorage.app',
    measurementId: 'G-FKF8X5YZWW',
  );
}
